spring:
  application: order-service
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    jdbcUrl: jdbc:h2:mem:ms-order?useSSL=false&serverTimezone=UTC
    username: sa
    password: 12345
server:
  port: 8085
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
management:
  server:
    port: 9095
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, mappings